# Generated by Django 5.0.6 on 2024-07-25 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_weblog', '0002_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_weblog.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='course',
            name='package',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
